name       : mediainfo
version    : '23.04'
release    : 25
source     :
    - https://mediaarea.net/download/source/mediainfo/23.04/mediainfo_23.04.tar.bz2 : 20397c5d46f30f6d995c6b162b6730599434b7f4693385e75106ef871f80fe62
license    : BSD-2-Clause
component  : multimedia.video
homepage   : https://mediaarea.net/en/MediaInfo
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libmediainfo)
    - desktop-file-utils
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    %make -C Project/GNU/CLI
    %make -C Project/GNU/GUI
install    : |
    %make_install -C Project/GNU/CLI
    %make_install -C Project/GNU/GUI
