name       : mediainfo
version    : 17.12
release    : 11
source     :
    - https://mediaarea.net/download/source/mediainfo/17.12/mediainfo_17.12.tar.gz : b557c8bc91ac5f2a7297c2a2c2c1a6305d4ec5d89745130b831ceb992595ce8e
license    : BSD-2-Clause
component  : multimedia.video
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(libmediainfo)
    - pkgconfig(sm)
    - desktop-file-utils
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    pushd Project/GNU/CLI
        %make
    popd
    pushd Project/GNU/GUI
        %make
    popd
install    : |
    pushd Project/GNU/CLI
        %make_install
    popd
    pushd Project/GNU/GUI
        %make_install
    popd

