name       : mediainfo
version    : 0.7.97
release    : 7
source     :
    - https://mediaarea.net/download/source/mediainfo/0.7.97/mediainfo_0.7.97.tar.xz : 16a522e9caee73dcb8bcab3244b02fc51257c24b4deba961de983698d4101782
license    : BSD-2-Clause
component  : multimedia.video
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(libmediainfo)
    - pkgconfig(sm)
    - desktop-file-utils
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    pushd Project/GNU/CLI
        %make
    popd
    pushd Project/GNU/GUI
        %make
    popd
install    : |
    pushd Project/GNU/CLI
        %make_install
    popd
    pushd Project/GNU/GUI
        %make_install
    popd

