name       : mediainfo
version    : '19.07'
release    : 20
source     :
    - https://old.mediaarea.net/download/source/mediainfo/19.07/mediainfo_19.07.tar.xz : 84a8991cec4f11e580fb40e922ce3f422d95f1ab489889df2366177969bb5e2c
license    : BSD-2-Clause
component  : multimedia.video
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(libmediainfo)
    - pkgconfig(sm)
    - desktop-file-utils
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    %make -C Project/GNU/CLI
    %make -C Project/GNU/GUI
install    : |
    %make_install -C Project/GNU/CLI
    %make_install -C Project/GNU/GUI
