name       : mediainfo
version    : '18.12'
release    : 18
source     :
    - https://old.mediaarea.net/download/source/mediainfo/18.12/mediainfo_18.12.tar.xz : 6d3c10859d0dd021851d20a01c73f1fe41565d5d198a37aa8bf424e1dc29f306
license    : BSD-2-Clause
component  : multimedia.video
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(ImageMagick)
    - pkgconfig(libmediainfo)
    - pkgconfig(sm)
    - desktop-file-utils
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    %make -C Project/GNU/CLI
    %make -C Project/GNU/GUI
install    : |
    %make_install -C Project/GNU/CLI
    %make_install -C Project/GNU/GUI
