name       : mediainfo
version    : 0.7.88
release    : 2
source     :
    - https://mediaarea.net/download/source/mediainfo/0.7.88/mediainfo_0.7.88.tar.xz : 853839f0dce758f97ab950069c73a2ea7b601f6712bbcee36d0bc2ee9f58f373
license    : BSD-2-Clause
component  : multimedia.video
summary    : MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
description: |
    MediaInfo is a convenient unified display of the most relevant technical and tag data for video and audio files.
builddeps  :
    - pkgconfig(libmediainfo)
    - pkgconfig(sm)
    - desktop-file-utils
    - imagemagick
    - wxwidgets-devel
setup      : |
    pushd Project/GNU/CLI
        %autogen
    popd
    pushd Project/GNU/GUI
        %autogen
    popd
build      : |
    pushd Project/GNU/CLI
        %make
    popd
    pushd Project/GNU/GUI
        %make
    popd
install    : |
    pushd Project/GNU/CLI
        %make_install
    popd
    pushd Project/GNU/GUI
        %make_install
        install -Dm00644 mediainfo-gui.desktop $installdir/usr/share/applications/mediainfo-gui.desktop
    popd
    install -Dm00644 Source/Resource/Image/MediaInfo.png $installdir/usr/share/pixmaps/mediainfo.png
